import logo from "../../../../assets/images/second.jpg";
import ECK01 from "../../../../assets/images/ECK-01-300x300.png";
import ECK09 from "../../../../assets/images/ECK-09-300x300.png";
import PK35 from "../../../../assets/images/PK-35-300x300.png";
import KS40 from "../../../../assets/images/KS-40-300x300.png";
import PG35 from "../../../../assets/images/PG-35-300x300.png";
import shortid from "shortid";

export const categories = {
  facadeStucco: {
    facadestucco: [
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "facadeStucco",
        src: PK35,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: " RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "facadeStucco",
        src: KS40,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: " RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "facadeStucco",
        src: PG35,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: " RL 103",
          price: "Цена за единицу:",
        },
      },
    ],
    bosses: [
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "bosses",
        src: logo,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: " RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "bosses",
        src: logo,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: "Anschluss: RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "bosses",
        src: logo,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: " RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "bosses",
        src: logo,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: "Anschluss: RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "bosses",
        src: logo,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: " RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "bosses",
        src: logo,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: "Anschluss: RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "bosses",
        src: logo,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: " RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "bosses",
        src: logo,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: "Anschluss: RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "bosses",
        src: logo,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: " RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "bosses",
        src: logo,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: "Anschluss: RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "bosses",
        src: logo,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: " RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "bosses",
        src: logo,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: "Anschluss: RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "bosses",
        src: logo,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: " RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "bosses",
        src: logo,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: "Anschluss: RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "bosses",
        src: logo,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: " RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "bosses",
        src: logo,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: "Anschluss: RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "bosses",
        src: logo,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: "Anschluss: RL 103",
          price: "Цена за единицу:",
        },
      },
    ],
    corner: [
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "corner",
        src: ECK01,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: " RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "corner",
        src: ECK01,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: " RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "corner",
        src: ECK01,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: " RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "corner",
        src: ECK09,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: " RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "corner",
        src: ECK09,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: " RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "corner",
        src: ECK09,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: " RL 103",
          price: "Цена за единицу:",
        },
      },
      {
        id: shortid.generate(),
        link: "/Product",
        title: "EN-123",
        type: "corner",
        src: ECK09,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: {
          title: "discription",
          size: "/28×28/кг: 0,5",
          connect: " RL 103",
          price: "Цена за единицу:",
        },
      },
    ],
    windowsills: [
      {
        id: 1,
        link: "",
        text: "",
        type: "",
        imgUrl: "",
        categorie: "",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    windowBar: [
      {
        id: shortid.generate(),
        link: "",
        text: "",
        type: "",
        imgUrl: "",
        categorie: "",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    mainCornice: [
      {
        id: shortid.generate(),
        link: "",
        text: "",
        type: "",
        imgUrl: "",
        categorie: "",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    pilaster: [
      {
        id: shortid.generate(),
        link: "",
        text: "",
        type: "",
        imgUrl: "",
        categorie: "",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    columns: [
      {
        id: shortid.generate(),
        link: "",
        text: "",
        type: "",
        imgUrl: "",
        categorie: "",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    miscellaneous: [
      {
        id: shortid.generate(),
        link: "",
        text: "",
        type: "",
        imgUrl: "",
        categorie: "",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
  },
  internal: {
    pictures: [
      {
        id: shortid.generate(),
        link: "",
        text: "",
        type: "pictures",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    ceilingAndWallMoldings: [
      {
        id: shortid.generate(),
        link: "",
        text: "",
        type: "ceiling and wall moldings",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    ceilingMirror: [
      {
        id: shortid.generate(),
        link: "",
        text: "",
        type: "ceiling mirror",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    decorativeCorners: [
      {
        id: shortid.generate(),
        link: "",
        text: "",
        type: "decorative corners",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    indirectLightStrips: [
      {
        id: shortid.generate(),
        link: "",
        text: "",
        type: "Indirect light strips",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    cassettes: [
      {
        id: shortid.generate(),
        link: "",
        text: "",
        type: "cassettes",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    lamps: [
      {
        id: shortid.generate(),
        link: "",
        text: "",
        type: "lamps",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    ornaments: [
      {
        id: shortid.generate(),
        link: "",
        text: "",
        type: "ornaments",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    pilaster: [
      {
        id: shortid.generate(),
        link: "",
        text: "",
        type: "pilaster",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    frameMoldings: [
      {
        id: shortid.generate(),
        link: "",
        text: "",
        type: "frame moldings",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    rosettes: [
      {
        id: shortid.generate(),
        link: "",
        text: "",
        type: "rosettes",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    columns: [
      {
        id: shortid.generate(),
        link: "",
        text: "",
        type: "columns",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    miscellaneous: [
      {
        id: shortid.generate(),

        link: "",
        text: "",
        type: "miscellaneous",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    supraport: [
      {
        id: shortid.generate(),
        link: "",
        text: "",
        type: "supraport",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
  },
  recommended: [],
};
