import logo from "../../../../images/three.jpg";

export const categories = {
  facadeStucco: {
    bosses: [
      {
        id: 1,
        link: "/Product",
        title: "EN-123",
        type: "bosses",
        src: logo,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: "",
      },
      {
        id: 1,
        link: "/Product",
        title: "EN-123",
        type: "bosses",
        src: logo,
        categorie: "facadeStucco",
        price: "€ 15.00",
        discription: "",
      },
    ],
    corner: [
      {
        id: 1,
        link: "",
        text: "",
        type: "",
        imgUrl: "",
        categorie: "",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    windowsills: [
      {
        id: 1,
        link: "",
        text: "",
        type: "",
        imgUrl: "",
        categorie: "",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    windowBar: [
      {
        id: 1,
        link: "",
        text: "",
        type: "",
        imgUrl: "",
        categorie: "",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    mainCornice: [
      {
        id: 1,
        link: "",
        text: "",
        type: "",
        imgUrl: "",
        categorie: "",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    pilaster: [
      {
        id: 1,
        link: "",
        text: "",
        type: "",
        imgUrl: "",
        categorie: "",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    columns: [
      {
        id: 1,
        link: "",
        text: "",
        type: "",
        imgUrl: "",
        categorie: "",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    miscellaneous: [
      {
        id: 1,
        link: "",
        text: "",
        type: "",
        imgUrl: "",
        categorie: "",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
  },
  internal: {
    pictures: [
      {
        id: 1,
        link: "",
        text: "",
        type: "pictures",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    ceilingAndWallMoldings: [
      {
        id: 1,
        link: "",
        text: "",
        type: "ceiling and wall moldings",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    ceilingMirror: [
      {
        id: 1,
        link: "",
        text: "",
        type: "ceiling mirror",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    decorativeCorners: [
      {
        id: 1,
        link: "",
        text: "",
        type: "decorative corners",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    indirectLightStrips: [
      {
        id: 1,
        link: "",
        text: "",
        type: "Indirect light strips",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    cassettes: [
      {
        id: 1,
        link: "",
        text: "",
        type: "cassettes",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    lamps: [
      {
        id: 1,
        link: "",
        text: "",
        type: "lamps",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    ornaments: [
      {
        id: 1,
        link: "",
        text: "",
        type: "ornaments",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    pilaster: [
      {
        id: 1,
        link: "",
        text: "",
        type: "pilaster",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    frameMoldings: [
      {
        id: 1,
        link: "",
        text: "",
        type: "frame moldings",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    rosettes: [
      {
        id: 1,
        link: "",
        text: "",
        type: "rosettes",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    columns: [
      {
        id: 1,
        link: "",
        text: "",
        type: "columns",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    miscellaneous: [
      {
        id: 1,
        link: "",
        text: "",
        type: "miscellaneous",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
    supraport: [
      {
        id: 1,
        link: "",
        text: "",
        type: "supraport",
        imgUrl: "",
        categorie: "internal",
        price: "",
        discription: "",
        translaterField: "",
      },
    ],
  },
  recommended: [],
};
